# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Users
first_user = User.create(name: 'Don G. Adams', photo: 'users_thumbnail\first_user.jpg', bio: 'Don is a freelance writer and editor who has a knack for finding adventure and inspiration in every corner of the world. He has visited over 30 countries and written about topics ranging from ancient temples to modern art. He is also a certified yoga instructor and a passionate advocate for mental health awareness. He believes that travel is not only a way to explore new places, but also a way to discover oneself. When he is not working or traveling, he enjoys reading, cooking, and spending time with his family and friends, who are always eager to hear his stories.')
second_user = User.create(name: 'Les J. Haley', photo: 'users_thumbnail\second_user.jpg', bio: 'Les is a freelance photographer and videographer who loves to capture the beauty and diversity of the world. He has worked with various clients and publications, such as National Geographic, Travel + Leisure, and CNN. He is also a avid traveler and adventurer, who has explored over 40 countries and experienced different cultures and cuisines. He is always looking for new challenges and opportunities to learn and grow. When he is not working or traveling, he enjoys playing guitar, watching movies, and spending time with his dog, Milo.')
third_user = User.create(name: 'Caroline G. Metcalf', photo: 'users_thumbnail\third_user.jpg', bio: 'Caroline is a freelance graphic designer and illustrator who creates stunning and unique artworks for various clients and projects. She has a degree in fine arts and a passion for visual storytelling. She is also a keen traveler and explorer, who has visited over 20 countries and learned from different cultures and styles. She is always looking for new inspiration and ways to express herself. When she is not working or traveling, she enjoys painting, reading, and spending time with her cat, Luna.')
fourth_user = User.create(name: 'Terry B. Benavidez', photo: 'users_thumbnail\fourth_user.jpg', bio: 'Terry is a freelance social media manager and content creator who helps brands and businesses grow their online presence and reach. She has a degree in marketing and a flair for writing engaging and catchy posts. She is also a passionate traveler and blogger, who has visited over 25 countries and shared her experiences and tips with her followers. She is always looking for new trends and opportunities to connect and collaborate. When she is not working or traveling, she enjoys dancing, cooking, and spending time with her friends.')
fifth_user = User.create(name: 'Rebecca J. Morris', photo: 'users_thumbnail\fifth_user.jpg', bio: 'Rebecca is a freelance web developer and coder who creates amazing and functional websites and apps for various clients and projects. She has a degree in computer science and a love for problem-solving and innovation. She is also a curious learner and explorer, who has visited over 15 countries and learned from different technologies and cultures. She is always looking for new challenges and ways to improve her skills. When she is not working or traveling, she enjoys gaming, knitting, and spending time with her family.')

# Posts
first_post = Post.create(author: first_user, title: 'First post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
second_post = Post.create(author: first_user, title: 'Second post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
third_post = Post.create(author: first_user, title: 'Third post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
fourth_post = Post.create(author: first_user, title: 'Fourth post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam..')
fifth_post = Post.create(author: second_user, title: 'Fifth post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
sixth_post = Post.create(author: second_user, title: 'Sixth post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
seventh_post = Post.create(author: second_user, title: 'Seventh post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
eighth_post = Post.create(author: third_user, title: 'Eight post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
ninht_post = Post.create(author: third_user, title: 'Nine post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
tenth_post = Post.create(author: fourth_user, title: 'Tenth post', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')

# Comments
first_comment = Comment.create(post: first_post, author: first_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
second_comment = Comment.create(post: first_post, author: second_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.' )
third_comment = Comment.create(post: first_post, author: third_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
fourth_comment = Comment.create(post: first_post, author: fourth_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
fifth_comment = Comment.create(post: first_post, author: fifth_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
sixth_comment = Comment.create(post: first_post, author: first_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
seventh_comment = Comment.create(post: second_post, author: third_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
eighth_comment = Comment.create(post: second_post, author: fourth_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
ninth_comment = Comment.create(post: third_post, author: first_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
tenth_comment = Comment.create(post: third_post, author: second_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
eleventh_comment = Comment.create(post: third_post, author: third_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
twelfth_comment = Comment.create(post: fourth_post, author: fourth_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
thirteenth_comment = Comment.create(post: fourth_post, author: fifth_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')
fourteenth_comment = Comment.create(post: fourth_post, author: second_user, text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis lorem eu nisi ullamcorper lacinia. Morbi vitae nisl id nisi tincidunt consequat. Quisque auctor, leo quis consequat sagittis, massa nisi elementum eros, at aliquet justo leo id lectus. Fusce vitae semper augue. In hac habitasse platea dictumst. Cras in lacus ut magna tincidunt rutrum. Curabitur quis nisl auctor, sollicitudin nibh vitae, mattis velit. Vivamus quis nunc et sapien ultricies aliquet. Praesent vel neque ut elit fringilla luctus. Suspendisse potenti. Donec sit amet lorem ac diam fermentum blandit. Etiam sit amet lacus sed erat malesuada faucibus. Sed id felis in leo tincidunt ornare. Nunc euismod, dolor eget sagittis tristique, sapien nisl condimentum turpis, nec lacinia arcu lorem non quam. Duis quis augue vitae nisi ullamcorper aliquam.')

# Likes
first_like = Like.create(post: first_post, author: first_user)
second_like = Like.create(post: first_post, author: second_user)
third_like = Like.create(post: first_post, author: third_user)
fourth_like = Like.create(post: first_post, author: fourth_user)
fifth_like = Like.create(post: first_post, author: fifth_user)
sixth_like = Like.create(post: second_post, author: second_user)
seventh_like = Like.create(post: seventh_post, author: third_user)
eighth_like = Like.create(post: second_post, author: fourth_user)
ninth_like = Like.create(post: third_post, author: first_user)
tenth_like = Like.create(post: fourth_post, author: second_user)